services:
  app:
    labels:
      traefik.enable: true
      traefik.http.routers.empires.rule: Host(`empires.anagraph.org`)
    mem_limit: 512m
    build:
      target: frankenphp_prod
    env_file: .env.local
    environment:
      SERVER_NAME: ":80"
      TRUSTED_PROXIES: REMOTE_ADDR
      DATABASE_URL: "sqlite:///%kernel.project_dir%/system/database/data/empires.db"
    volumes:
      - db_data:/app/system/database/data
    networks:
      - proxy
      - default

volumes:
  db_data:

networks:
  proxy:
    external: true
    name: reverse_proxy_network
