services:
  webserver:
    build:
      context: .
      dockerfile: system/Containerfile
    depends_on:
      - backend
    volumes:
      - ./system/webserver:/etc/caddy:ro
      - webserver_data:/data:rw
      - webserver_config:/config:rw

  backend:
    build:
      context: .
      dockerfile: system/Containerfile

volumes:
  webserver_data:
  webserver_config:
