ast:
    requirements:
        start: { basic: {}, expert: {} }
        stone_age: { basic: {}, expert: {} }
        early_bronze_age: { basic: { cities: 2 }, expert: { cities: 3 } }
        middle_bronze_age: { basic: { cities: 3, advances: 3 }, expert: { cities: 3, advance_points: 5 } }
        late_bronze_age: { basic: { cities: 3, advances: 3, min_advance_cost: 100 }, expert: { cities: 4, advances: 12 } }
        early_iron_age: { basic: { cities: 4, advances: 2, min_advance_cost: 200 }, expert: { cities: 5, advances: 10, max_advance_cost: 99, advance_points: 38 } }
        late_iron_age: { basic: { cities: 5, advances: 3, min_advance_cost: 200 }, expert: { cities: 6, advances: 17, max_advance_cost: 99, advance_points: 56 } }

    tracks:
        basic:
            standard:
                empires: [assyria, maurya, babylon, dravidia, hatti, kushan, rome, persia, nubia, hellas, indus, egypt]
                spans: { start: 1, stone_age: 4, early_bronze_age: 3, middle_bronze_age: 3, late_bronze_age: 3, early_iron_age: 1, late_iron_age: 1 }
            slow_starter:
                empires: [minoa, saba]
                spans: { start: 1, stone_age: 5, early_bronze_age: 3, middle_bronze_age: 2, late_bronze_age: 3, early_iron_age: 1, late_iron_age: 1 }
            extended_early_bronze:
                empires: [celt, carthage, iberia, parthia]
                spans: { start: 1, stone_age: 4, early_bronze_age: 4, middle_bronze_age: 2, late_bronze_age: 3, early_iron_age: 1, late_iron_age: 1 }
        expert:
            standard:
                empires: [assyria, maurya, celt, babylon, carthage, dravidia, hatti, rome, persia, nubia, hellas, indus, egypt, parthia]
                spans: { start: 1, stone_age: 4, early_bronze_age: 3, middle_bronze_age: 3, late_bronze_age: 3, early_iron_age: 1, late_iron_age: 2 }
            extended_stone_age:
                empires: [minoa, saba, kushan, iberia]
                spans: { start: 1, stone_age: 5, early_bronze_age: 2, middle_bronze_age: 3, late_bronze_age: 3, early_iron_age: 1, late_iron_age: 2 }
