civilizations:
    assyria:
        ranking: 3
        name: "assyria"
        demonym: "assyrians"
        adjective: "assyrian"
        people_icon:
        ship_icon:
        city_icon:
        color: "#51cbf1"

    carthage:
        ranking: 7
        name: "carthage"
        demonym: "carthaginians"
        adjective: "carthaginian"
        people_icon:
        ship_icon:
        city_icon:
        color: "#ec920d"

    celt:
        ranking: 5
        name: "celt"
        demonym: "celts"
        adjective: "celtic"
        people_icon:
        ship_icon:
        city_icon:
        color: "#46a73a"

    egypt:
        ranking: 17
        name: "egypt"
        demonym: "egyptians"
        adjective: "egyptian"
        people_icon:
        ship_icon:
        city_icon:
        color: "#fbddc2"

    hatti:
        ranking: 9
        name: "hatti"
        demonym: "hattians"
        adjective: "hattian"
        people_icon:
        ship_icon:
        city_icon:
        color: "#f08eba"

    hellas:
        ranking: 15
        name: "hellas"
        demonym: "hellenes"
        adjective: "hellenic"
        people_icon: "hellas_people.webp"
        ship_icon: "hellas_ship.webp"
        city_icon: "hellas_city.webp"
        color: "#f08eba"

    iberia:
        ranking: 13
        name: "iberia"
        demonym: "iberians"
        adjective: "iberian"
        people_icon:
        ship_icon:
        city_icon:
        color: "#dddddd"

    minoa:
        ranking: 1
        name: "minoa"
        demonym: "minoans"
        adjective: "minoan"
        people_icon:
        ship_icon:
        city_icon:
        color: "#a4ce53"

    rome:
        ranking: 11
        name: "rome"
        demonym: "romans"
        adjective: "roman"
        people_icon:
        ship_icon:
        city_icon:
        color: "#e50082"

    babylon:
        ranking: 6
        name: "babylon"
        demonym: "babylonians"
        adjective: "babylonian"
        people_icon:
        ship_icon:
        city_icon:
        color: "#7d7e80"

    dravidia:
        ranking: 8
        name: "dravidia"
        demonym: "dravidians"
        adjective: "dravidian"
        people_icon:
        ship_icon:
        city_icon:
        color: "#302f88"

    indus:
        ranking: 16
        name: "indus"
        demonym: "indus people"
        adjective: "indus"
        people_icon:
        ship_icon:
        city_icon:
        color: "#248a47"

    kushan:
        ranking: 10
        name: "kushan"
        demonym: "kushans"
        adjective: "kushan"
        people_icon:
        ship_icon:
        city_icon:
        color: "#5a0b0e"

    maurya:
        ranking: 4
        name: "maurya"
        demonym: "mauryans"
        adjective: "mauryan"
        people_icon:
        ship_icon:
        city_icon:
        color: "#e32123"

    nubia:
        ranking: 14
        name: "nubia"
        demonym: "nubians"
        adjective: "nubian"
        people_icon:
        ship_icon:
        city_icon:
        color: "#31a79c"

    parthia:
        ranking: 18
        name: "parthia"
        demonym: "parthians"
        adjective: "parthian"
        people_icon:
        ship_icon:
        city_icon:
        color: "#524f22"

    persia:
        ranking: 12
        name: "persia"
        demonym: "persians"
        adjective: "persian"
        people_icon:
        ship_icon:
        city_icon:
        color: "#89228c"

    saba:
        ranking: 12
        name: "saba"
        demonym: "sabaeans"
        adjective: "sabaean"
        people_icon:
        ship_icon:
        city_icon:
        color: "#eb6727"

regions:
    west:
        name2019: "Western Empires"
        name2024: "Mega Empires: The West"
        civilizations: ["assyria", "carthage", "celt", "egypt", "hatti", "hellas", "iberia", "minoa", "rome"]

    east:
        name2019: "Eastern Empires"
        name2024: "Mega Empires: The East"
        civilizations: ["babylon", "dravidia", "indus", "kushan", "maurya", "nubia", "parthia", "persia", "saba"]

scenarios:
    5_east: ["babylon", "nubia", "parthia", "persia", "saba"]
    5_west: ["assyria", "egypt", "hatti", "hellas", "minoa"]
    6_east: ["babylon", "indus", "kushan", "parthia", "persia", "saba"]
    6_west: ["carthage", "hatti", "hellas", "iberia", "minoa", "rome"]
    7_east: ["babylon", "indus", "kushan", "nubia", "parthia", "persia", "saba" ]
    7_west: ["assyria", "carthage", "egypt", "hatti", "hellas", "minoa", "rome"]
    8_east: ["babylon", "dravidia", "indus", "kushan", "maurya", "parthia", "persia", "saba"]
    8_west: ["assyria", "carthage", "egypt", "hatti", "hellas", "iberia", "minoa", "rome"]
    9_east: ["babylon", "dravidia", "indus", "kushan", "maurya", "nubia", "parthia", "persia", "saba"]
    9_west: ["assyria", "carthage", "celt", "egypt", "hatti", "hellas", "iberia", "minoa", "rome"]
    10: ["assyria", "egypt", "hatti", "hellas", "minoa", "babylon", "nubia", "parthia", "persia", "saba"]
    11: ["assyria", "egypt", "babylon", "dravidia", "indus", "kushan", "maurya", "nubia", "parthia", "persia", "saba"]
    12:
        east: ["assyria", "babylon", "nubia", "parthia", "persia", "saba"]
        west: ["carthage", "egypt", "hatti", "hellas", "minoa", "rome"]
    13:
        east: ["assyria", "egypt", "babylon", "nubia", "parthia", "persia", "saba"]
        west: ["carthage", "hatti", "hellas", "iberia", "minoa", "rome"]
    14:
        east: ["assyria", "egypt", "babylon", "nubia", "parthia", "persia", "saba"]
        west: ["carthage", "celt", "hatti", "hellas", "iberia", "minoa", "rome"]
    15:
        east: ["assyria", "babylon", "indus", "kushan", "nubia", "parthia", "persia", "saba"]
        west: ["carthage", "egypt", "hatti", "hellas", "iberia", "minoa", "rome"]
    16:
        east: ["assyria", "babylon", "indus", "kushan", "nubia", "parthia", "persia", "saba"]
        west: ["carthage", "celt", "egypt", "hatti", "hellas", "iberia", "minoa", "rome"]
    17:
        east: ["babylon", "dravidia", "indus", "kushan", "maurya", "nubia", "parthia", "persia", "saba"]
        west: ["assyria", "carthage", "egypt", "hatti", "hellas", "iberia", "minoa", "rome"]
    18:
        east: ["babylon", "dravidia", "indus", "kushan", "maurya", "nubia", "parthia", "persia", "saba"]
        west: ["assyria", "carthage", "celt", "egypt", "hatti", "hellas", "iberia", "minoa", "rome"]

limits:
    max_cities: 9
    max_population: 55
    max_ships: 4
    modes: ["basic", "expert"]
    min_players: 3
    max_players: 18
